### ISSUE TITLE
npm run dev  时css 编译报错

### ISSUE THREAD

**Issue by Maple13** [CharlieLau/gaea-editor-vue#1]
我在使用`vue-cli`创建的项目中引入`gaea-editor-vue` 后, 按照 README 操作, 运行`npm run dev` 时报错, 提示
<img width="795" alt="wx20180408-173231 2x" src="https://user-images.githubusercontent.com/11918457/38465792-d8c4bd82-3b52-11e8-9b87-bf2d4d554b9a.png">

请问有遇到此类问题吗? 
根据报错提示, 发现与`gaea-editor-vue`中`plugins`文件夹下的 style.js 相关

**Comment by CharlieLau** [comment]
好滴，我还开发build的包，周末开发，然后你更一个版本就行，请耐性等待下，谢谢

**Comment by Maple13** [comment]
感谢回复, 期待中

**Comment by Maple13** [comment]
好的, 感谢
